### ISSUE TITLE
I can't turn on my cell phone camera(z2_plus/z2_row)

### ISSUE THREAD

**Issue by hxsstime** [RikkaApps/Riru#14]
Phone model: ZUK Z2 Plus(z2_plus) / ZUK Z2 PRO(z2_row)
ROM Version: AEX 6.2
Crash Log Links: https://del.dog/recohideri

I can't turn on my cell phone camera.

time: 1548307111394
msg: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
stacktrace: java.lang.RuntimeException: Unable to resume activity {org.lineageos.snap/com.android.camera.CameraLauncher}: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3824)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3856)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at com.android.camera.PhotoModule.initializeFocusManager(PhotoModule.java:2825)
	at com.android.camera.PhotoModule.onResumeBeforeSuper(PhotoModule.java:2599)
	at com.android.camera.CameraActivity.onResume(CameraActivity.java:1862)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1413)
	at android.app.Activity.performResume(Activity.java:7300)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3816)
	... 11 more

**Comment by LBA97** [comment]
Same issue here, with the same phone model and is version

**Comment by RikkaW** [comment]
Strange problem, maybe camera daemon not started?

To verify this guess, run these commands in adb shell or terminal app with root and paste the result here.
`dumpsys media.camera | grep "maps to"`
`ps -e | grep camera`

Also log from boot may help.

**Comment by hxsstime** [comment]
> Strange problem, maybe camera daemon not started?
> 
> To verify this guess, run these commands in adb shell or terminal app with root and paste the result here.
> `dumpsys media.camera | grep "maps to"`
> `ps -e | grep camera`
> 
> Also log from boot may help.


> Strange problem, maybe camera daemon not started?
> 
> To verify this guess, run these commands in adb shell or terminal app with root and paste the result here.
> `dumpsys media.camera | grep "maps to"`
> `ps -e | grep camera`
> 
> Also log from boot may help.

![image](https://user-images.githubusercontent.com/46912897/51885961-c100d780-23c8-11e9-8e2c-2933d903a334.png)
This?

**Comment by RikkaW** [comment]
@hxsstime These are two commands, you paste them in one line :(

**Comment by hxsstime** [comment]
> @hxsstime These are two commands, but you have pasted them in one line :(

![image](https://user-images.githubusercontent.com/46912897/51889601-f0b5dc80-23d4-11e9-9663-5be4a098c9e2.png)

**Comment by hxsstime** [comment]
> > @hxsstime These are two commands, but you have pasted them in one line :(
> 
> ![image](https://user-images.githubusercontent.com/46912897/51889601-f0b5dc80-23d4-11e9-9663-5be4a098c9e2.png)



> @hxsstime These are two commands, but you have pasted them in one line :(

![image](https://user-images.githubusercontent.com/46912897/51889719-34104b00-23d5-11e9-9441-875bddb664c0.png)

**Comment by RikkaW** [comment]
`su` first

**Comment by hxsstime** [comment]
> @hxsstime `su` first

![image](https://user-images.githubusercontent.com/46912897/51890238-8bfb8180-23d6-11e9-99a6-99b367061be5.png)

**Comment by hxsstime** [comment]
> Seems camera daemon really not started.
> Need log from boot :(

Crash Log URL？
https://del.dog/tonoyipifu

**Comment by RikkaW** [comment]
> > Seems camera daemon really not started.
> > Need log from boot :(
> 
> Crash Log URL？
> https://del.dog/tonoyipifu

The whole device log from boot, use logcat ASAP the device boot.

**Comment by hxsstime** [comment]
> > > Seems camera daemon really not started.
> > > Need log from boot :(
> > 
> > 
> > Crash Log URL？
> > https://del.dog/tonoyipifu
> 
> The whole device log from boot, use logcat ASAP the device boot.

[Z2_PLUS(AEX6.2)2019-01-30.log](https://github.com/RikkaApps/Riru/files/2810546/Z2_PLUS.AEX6.2.2019-01-30.log)

**Comment by xiuluo** [comment]
This bug has been fixed in AEX 6.3 and can be close this issue. I have tested on ZUK Z2 PRO(z2_row).

**Comment by hxsstime** [comment]
Yes, the problem has been fixed, the previous use of mobile browser can not reply.
Sorry for the late reply, thank you.
