### ISSUE TITLE
Riru 25.4.1 Security exception during installation

### ISSUE THREAD

**Issue by Mark-Joy** [RikkaApps/Riru#219]
**Information:**

- Except Riru itself, all other Magisk modules are disabled: [Yes]
- Riru version: 25.4.1
- Magisk version: 22.1
- Android version: Android 9
- Device: Redmi Note 8 Pro

**Logs:**

[magisk_install_log_2021-04-15T13:57:29Z.log](https://github.com/RikkaApps/Riru/files/6316001/magisk_install_log_2021-04-15T13.57.29Z.log)

**Describe the bug:**

I got a security exception during installation. Don't know if it has any effect to the whole installation.

```
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: app.apk.sha256sum
- Verified app.apk
avc:  could not determine enforcing mode: Permission denied
Security exception: Reverse mode only supported from shell

java.lang.SecurityException: Reverse mode only supported from shell
	at com.android.server.pm.PackageInstallerSession.doWriteInternal(Unknown Source:159)
	at com.android.server.pm.PackageInstallerSession.doWriteInternal(Unknown Source:6)
	at com.android.server.pm.PackageInstallerSession.write(Unknown Source:0)
	at android.content.pm.PackageInstaller$Session.write(Unknown Source:6)
	at com.android.server.pm.PackageManagerShellCommand.doWriteSplit(Unknown Source:131)
	at com.android.server.pm.PackageManagerShellCommand.runInstall(Unknown Source:66)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(Unknown Source:994)
	at android.os.ShellCommand.exec(Unknown Source:41)
	at com.android.server.pm.PackageManagerService.onShellCommand(Unknown Source:12)
	at android.os.Binder.shellCommand(Unknown Source:0)
	at android.os.Binder.onTransact(Unknown Source:144)
	at android.content.pm.IPackageManager$Stub.onTransact(Unknown Source:21)
	at com.android.server.pm.PackageManagerService.onTransact(Unknown Source:0)
	at android.os.Binder.execTransact(Unknown Source:65)

```

Please let me know how to fix it.

**Comment by canyie** [comment]
Try #223
